NUMBER_OF_CLASS_DAYS = 5

# There are 2 types of penalty COEFFICIENT_PREFERENCE_* and COEFFICIENT_SLOT_PENALTY_*.
# The 2 types can be combined, but the same type cannot.
# The smaller the value, the higher the priority of the coefficient.
COEFFICIENT_PREFERENCE_STRONG_PREFERENCE = -30
COEFFICIENT_PREFERENCE_IDEALLY_YES = -20
COEFFICIENT_PREFERENCE_NEUTRAL = 0
COEFFICIENT_SLOT_PENALTY_FIRST_HOUR = 10
COEFFICIENT_PREFERENCE_PREFERABLY_NOT = 20
COEFFICIENT_PREFERENCE_IF_NOT_OTHERWISE_POSSIBLE = 30
COEFFICIENT_SLOT_PENALTY_EVENING_HOURS = 50
COEFFICIENT_PREFERENCE_NOT_AVAILABLE = 100
COEFFICIENT_SLOT_PENALTY_LUNCH_BREAK = 1000
